# Generated by Django 3.0.6 on 2020-05-21 04:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('passwd', models.CharField(blank=True, max_length=100)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'INACTIVE')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(default=None, max_length=100)),
                ('class_count', models.IntegerField(default=0)),
                ('enrolled_students_list', models.FileField(upload_to='studentList/')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'INACTIVE')], default=1, max_length=100)),
                ('teacher', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
    ]
